name: Run main.ts

on:
  workflow_dispatch:
  schedule:
    # Standard Time (Last Sunday of October to Last Saturday of March)
    - cron: '0 8 * 1-3 *'
    - cron: '0 8 * 10-12 *'
    # Daylight Saving Time (Last Sunday of March to Last Saturday of October)
    - cron: '0 7 * 3-10 *'

jobs:
  run-main:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
    
    - name: Install dependencies
      working-directory: ./wordguesser
      run: npm ci
      
    - name: Build
      working-directory: ./wordguesser
      run: npm run build

    - name: Run main.ts
      working-directory: ./wordguesser
      env:
        API_BASE_URL: ${{ secrets.API_URL }}
      run: node dist/main.js > /dev/null

    - name: Send file content to Discord webhook
      run: |
        FILE_CONTENT=$(jq -Rs . < ./wordguesser/output.txt)
        PAYLOAD=$(jq -n --arg content "$FILE_CONTENT" '{embeds: [{title: "Här är dagens ordel!", description: $content}]}')
        curl -X POST \
          -H "Content-Type: application/json" \
          -d "$PAYLOAD" \
          ${{ secrets.DISCORD_WEBHOOK }}
    
